

#define MMIO_ADDR(addr) ((uint8_t*)(void*)(addr))
#define MMIO_ADDR_FRAME_BUFFER_INT (MMIO_ADDR(0x8000))
#define MMIO_ADDR_FRAME_BUFFER_DIS (MMIO_ADDR(0x8000))

#define MMIO_ADDR_FRAME_BUFFER_SWAP (MMIO_ADDR(0x8000))
#define MMIO_ADDR_CONTROLLER_BASE (MMIO_ADDR(0x8000))

#define MMIO_ADDR_CONTROLLER1 (MMIO_ADDR_CONTROLLER_BASE + 0)
#define MMIO_ADDR_CONTROLLER2 (MMIO_ADDR_CONTROLLER_BASE + 16)
